Merge fixes. All tests pass, except: {{{ ====================================================================== FAIL: Doctest: fipy.viewers.vtkViewer.vtkCellViewer.VTKCellViewer._test ----------------------------------------------------------------------     AttributeError: 'VTKCellViewer' object has no attribute '_variableClass'
======================================================================
FAIL: Doctest: fipy.viewers.vtkViewer.vtkFaceViewer.VTKFaceViewer._test
----------------------------------------------------------------------
    AttributeError: 'VTKFaceViewer' object has no attribute '_variableClass'

======================================================================
FAIL: Doctest: examples.levelSet.electroChem.howToWriteAScript
----------------------------------------------------------------------
Failed example:
    print catalystVar.allclose(loadtxt(filepath), rtol=1e-4)
Expected:
    1
Got:
    False

======================================================================
FAIL: Doctest: examples.levelSet.electroChem.simpleTrenchSystem
----------------------------------------------------------------------
Failed example:
    runSimpleTrenchSystem(numberOfSteps=5, displayViewers=False)
Expected:
    1
Got:
    False
}}}

The first two will be remedied once r4190 is merged in. The second two 
have been failing for awhile and I'll sort them out once the branch is up 
to date.


git-svn-id: svn+ssh://code.matforge.org/fipy/branches/variableMeshes@4428 d80e17d7-ff13-0410-a124-85740d801063