Add diagnostics for incompatible packages
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - gmsh=3.0.6
  - pysparse
Use "conda search <package> --info" to see the dependencies for each package.
```